### ISSUE TITLE
cat | aaa の挙動が安定しない

### ISSUE THREAD

**Issue by syamashi** [syamashi/minishell#153]
```
bash-3.2$ cat | aaa
bash: aaa: command not found
// 読み込み待機
```
```
minishell$ cat | aaa
minishell: No such file or directory
minishell$ ddd
minishell: No such file or directory
minishell$ ddd
// 読み込み待機？
```

なんどかコマンドを打ったあとに、catの入力待ちのような状態になる

**Comment by syamashi** [comment]
```
waitpid(cpid, &status, 0) < 0
```
waitのタイミング？が不安定なのかもしれません。
挙動が意味不明すぎてなんとも・・・。
場合によってはゾンビ化してしまいました。

process_managerの中でwaitせず、抜けたあとwaitをすれば、少なくとも、catまちとGNLまちがいったりきたりしないような実装にはなりそうかなと思ってます

**Comment by syamashi** [comment]
ゾンビ化だとしたらNG要件かも、これ明日いちばんがんばる

**Comment by hariboten** [comment]
fixed
最後段プロセスだけでなく子プロセスは全てwaitする。そのうえでpipeを閉じるところで閉じればSIGPIPEでいいかんじにプロセスが終了する。
