### ISSUE TITLE
Builtin command export

### ISSUE THREAD

**Issue by hariboten** [syamashi/minishell#16]

**Comment by syamashi** [comment]
気づいてること
・keyの1文字目数字NG
・keyの2文字目以降、alnumかアンダーバーのみ有効
・=がなければvalueはNULL
・exportの表示は、key="value"
・もしvalueに$や"がきたら\$ \"でエスケープをつけて表示。
-- value自体にエスケープは不要。
-- value判定する時点で文字列属性（すでに環境変数は展開されていて、コマンド分けしないもの）
・exportはsortされて表示。クイックソートやる？
・keyが存在するものは上書き。なければ追加

**Comment by syamashi** [comment]
https://github.com/syamashi/minishell/commit/4978734395635fd5ee48c981492233d8122408f3
・minishell起動後、listをクイックソート(O(NlogN))
・export a=aaaを追加する場合。key:'a'の入れる場所を探索(O(N))
