### ISSUE TITLE
error_flagが立っていても、builtin関数の処理が行われる

### ISSUE THREAD

**Issue by syamashi** [syamashi/minishell#40]
minishell > export a=" a"; echo a > a$a 
minishell: a$a: ambiguous redirect
a

**Comment by hariboten** [comment]
ビルトイン実行前にエラーフラグ参照することで修正
終了ステータスは-1にしました。

ついでに最初のコマンドがビルトインかつパイプが次につながってる場合に最初のビルトインだけ実行して終わる処理になってたのでそれも修正
