### ISSUE TITLE
cat /dev/random | head -c 100 | wc -c

### ISSUE THREAD

**Issue by syamashi** [syamashi/minishell#56]
cat /dev/randomが出力し続けてしまう。

waitのタイミングを、最後の親がまとめて処理するとか？

https://keiorogiken.wordpress.com/2017/12/15/%E3%82%B7%E3%82%A7%E3%83%AB%E3%81%AE%E5%A4%9A%E6%AE%B5%E3%83%91%E3%82%A4%E3%83%97%E3%82%92%E8%87%AA%E4%BD%9C%E3%81%97%E3%81%A6%E3%81%BF%E3%82%8B/

**Comment by hariboten** [comment]
正しくは cat /dev/random | head -c 100

process_manager内のwaitpidをif (!next)のときのみ実行することで対応
この修正は他のバグを生む可能性がありそう……
