### ISSUE TITLE
✗ "ls -la | wtf"　の戻り値が違う

### ISSUE THREAD

**Issue by syamashi** [syamashi/minishell#71]
✗ "ls -la | wtf"

Your exit status : 0
Expected exit status : 127

**Comment by syamashi** [comment]
わかもれ
bash-3.2$ ls -la | wtf
bash: wtf: command not found
bash-3.2$ echo $?
127

minishell
ls -la | wtf
minishell: No such file or directory
echo $?
1

エラーメッセージと戻り値が違っている

**Comment by hariboten** [comment]
exit status fixed in #93 
error message problem discussing in #87
