### ISSUE TITLE
複数の数字付きリダイレクト対応

### ISSUE THREAD

**Issue by syamashi** [syamashi/minishell#77]
```
#include <unistd.h>

int main()
{
	write(1, "strout\n", 7);
	write(2, "strerr\n", 7);
	write(3, "dummy3\n", 7);
	write(4, "dummy4\n", 7);
}
```
./a.out 1>file1 2>file2 3>file3 4>file4

file1: "strout\n"
file2: "strerr\n"
file3: "dummy3\n"
file4: "dummy4\n"

exにもってるfd_outが1つだけど、数字付きfdを処理するためには、リダイレクトの数だけfd_outをもっておかないといけない？

**Comment by hariboten** [comment]
数字つきリダイレクトを実装するならパース段階のエラーメッセージを2>で指定された先に出さなきゃいけないのでそのタイミングが今の切り分けのままでは難しいですね。

それを除いたらfd_in, fd_out以外にfd_errを追加して標準エラーにdup2するみたいな形になるんじゃないですか……？

って思ったけどこれ3>fileとか4>fileとかにも対応しなきゃならないんですか？？そうなるとリダイレクトするfdをmap形式で保持する必要がありますね……
それと ./a.out 1>2 2>1　とか 1>2 2>3 3>1みたいなケースでどうなるのかとかも検証しないといけないかもです

**Comment by syamashi** [comment]
```
2>a 2>b 2>c

fd = open(a) // 3
backup = dup(2) // 10
dup2(2, 3)
これを、bとcにも。

復元フェーズ
dup2(2, 12)
dup2(2, 11)
dup2(2, 10)
```
こんな感じのことをしてみようか。

**Comment by syamashi** [comment]
<没>
1案おもいつきました。
・echoのfd出力とか、1に固定する
・parseの段階で1>file がきたら、dup2(fd, 1)など、1の場所をかえる。
・セミコロン単位の実行が終わったらfd1を復元する


```
2>file 2>file 2>file

こんなのを想定。

int main()
{
    int fd = open("file", O_WRONLY | O_CREAT | O_TRUNC, 0666);
    int backup1 = dup(2);
    dup2(fd, 2);
    close(fd);

    fd = open("file", O_WRONLY | O_CREAT | O_TRUNC, 0666);
    int backup2 = dup(2);
    dup2(fd, 2);
    close(fd);

    fd = open("file", O_WRONLY | O_CREAT | O_TRUNC, 0666);
    int backup3 = dup(2);
    dup2(fd, 2);
    close(fd);

    write(2, "strerr\n", 7);

    dup2(backup3, 2);
    close(backup3);
    dup2(backup2, 2);
    close(backup2);
    dup2(backup1, 2);
    close(backup1);
}
```

これをする場合、fdの復元はセミコロン単位でなく、パイプ単位でした。
セミコロン単位で先にファイルを開くことができず、かみ合わないため頓挫。

**Comment by syamashi** [comment]
commentの、パース中のエラーメッセージをファイル内 2>file にいれることはできました！

問題が。。
aaa 2>file | bbb

bbbのエラーを、普通にSTDERRで出すところが、fileに入ってしまうので、pipeごとにbackupを復元させる必要がある？

今はセミコロン単位ですべてのファイルを開いた後、launchに入っているんでしたっけ。
pipeごとに、fd開いて、pipe見終わったらbackupで戻す、をしないといけないかもしれないですか。

m_shじゃなくて、ex_listにbackupをいれて、pipeうつるごとにbackup復旧か

**Comment by syamashi** [comment]
https://github.com/syamashi/minishell/commit/0a17c720d7f130c19d1ce19102856f87e1dd5ee5
fd012だけ部分実装
