### ISSUE TITLE
getenv的な関数がほしい

### ISSUE THREAD

**Issue by hariboten** [syamashi/minishell#8]
char *getenv(t_list *env_list, char *key)

arg
- env_list minishell構造体内にある環境変数リスト。t_exec->envpを渡す仕様でも可。
- key 環境変数のキー。具体的にはPATHの値が知りたい。

return 
- keyに対応したvalue

備考
今の所必要な変数がPATHのみなのでgetpathでも可

@syamashi 
　よろしくお願いします。

**Comment by syamashi** [comment]
parse7_exinit.c
```
char	*value_get(char	*key, t_minishell *m_sh)
{
	int		len;
	t_list	*mov;
	char	*dkey;
	
	if (!ft_strncmp(key, "?", 2))
		return (ft_itoa(m_sh->exit_status));
	else
	{
		len = ft_strlen(key);
		if (len == 0)
			return (ft_strdup(""));
		mov = m_sh->env_list;
		while (mov)
		{
			dkey = ((t_dict *)mov->content)->key;
			if (!ft_strncmp(key, dkey, len + 1))
				return (ft_strdup(((t_dict *)mov->content)->value));
			mov = mov->next;
		}
	}
	return (ft_strdup(""));
}
```

が使えるかも！
・ヒットしなければ空文字かえります
・malloc失敗ならNULLがかえります

**Comment by syamashi** [comment]
char	*value_get(char *key, t_minishell *m_sh)
{
	int		len;
	t_list	*mov;
	char	*dkey;

	if (!key)
		return (NULL);
	if (!ft_strncmp(key, "?", 2))
		return (ft_itoa(m_sh->exit_status));
	else
	{
		len = ft_strlen(key);
		if (len == 0)
			return (ft_strdup(""));
		mov = m_sh->env_list;
		while (mov)
		{
			dkey = ((t_dict *)mov->content)->key;
			if (!ft_strncmp(key, dkey, len + 1))
				return (ft_strdup(((t_dict *)mov->content)->value));
			mov = mov->next;
		}
	}
	return (NULL);
}

やはり変更。存在しない場合を判定したいので、NULLを返すようにしました

**Comment by hariboten** [comment]
（おそらく）解決しました。ありがとうございます
