### ISSUE TITLE
存在しないバイナリを指定したときのエラーコード

### ISSUE THREAD

**Issue by syamashi** [syamashi/minishell#93]
bash-3.2$ /bin/asdf/asdf ; echo $?
bash: /bin/asdf/asdf: No such file or directory
127

bash-3.2$ /bin/ls/asdf ; echo $?
bash: /bin/ls/asdf: Not a directory
126

**Comment by hariboten** [comment]
/bin/asdf ←存在しない
/bin/asdf/asdf ←存在しない
/bin/ls　←バイナリ
/bin/ls/asdf ←存在しない

execvpで実行ファイルをサーチする方法の違いなんですよね……。
絶対パスでバイナリを指定してるのにわざわざdirectoryを開きにいってるのわけわからん

**Comment by hariboten** [comment]
```
/bin/ls/asdf; echo $?
minishell: Not a directory
1
/bin/asdf/asdf; echo $?
minishell: No such file or directory
1
```
違いました。エラーコード自体はあってますねENOTDIRはexecveが出してます。それを終了ステータスに格納できてないのが問題でした。

**Comment by hariboten** [comment]
errno
ENOTDIR 20
ENOENT 1

これをどうやって126と127にするか思いつかない

**Comment by hariboten** [comment]
https://linuxjm.osdn.jp/html/GNU_bash/man1/bash.1.html

> 終了ステータス
> 
> 実行したコマンドの終了ステータスは、waitpid システムコールまたはそれに相当する関数が返した値です。 終了ステータスは 0 から 255 の値を取りますが、後述するように、 125 より大きい値は特別にシェルによって使われることがあります。 シェルの組み込みコマンドや複合コマンドの終了ステータスも、 同じ範囲に限定されています。 環境によっては、シェルは仕様で決められた失敗のモードを表す 特別の値を使います。
> 
> シェルは、終了コード 0 で終了したコマンドは正常終了したとみなします。 終了コード 0 は成功を示します。 0 以外の終了コードは失敗を示します。 あるコマンドが致命的なシグナル N で終了したときには、 bash は「128+N」の値を終了ステータスに使います。
> 
> コマンドが見つからなかった場合には、 そのコマンドを実行するために生成された子プロセスが ステータス 127 を返します。 コマンドが見つかったけれど実行できなかった場合には、 ステータスは 126 です。
> 
> 展開やリダイレクションの際にエラーが発生し コマンドが失敗した場合には、 0 より大きい終了ステータスが返されます。
> 
> シェルの組み込みコマンドは、 成功した場合にはステータス 0 (真) を返し、 実行中にエラーが起こった場合には 0 でない値 (偽) を返します。 組み込みコマンドは全て、正しくない使い方であることを示すのに 終了ステータス 2 を返します。
> 
> bash 自身が返す終了ステータスは、文法エラーが起きた場合を除き、 実行した最後のコマンドの終了ステータスです。 文法エラーの場合には 0 でない値が終了ステータスとなります。 後述の組み込みコマンド exit も参照してください。

**Comment by hariboten** [comment]
とりあえず冒頭の２つのパターンでは正しく終了ステータスが設定されるようになりました。
絶対パス相対パスのケースでは正常に動作すると思います。
PATHからバイナリを探すケースでまだ問題が見つかるかも知れません
